<!DOCTYPE HTML>
<html lang="en-US">
<?php echo view("head");?>
<body>
<!--==================================================-->
<!-- Start cryptobit Main Menu Area -->
<!--==================================================-->
<?php echo view("header");?>
<!-- Cryptobit Mobile Menu Area -->
<!--==================================================-->
<!-- End cryptobit main menu Area -->
<!--==================================================-->

<!-- ===============//breatcome area start here \\================= -->
<div class="clearfix" style="clear: both;"></div>
<div class="breatcome-area d-flex align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breatcome-content text-center">
                    <div class="breatcome-title">
                        <h1>Términos y condiciones</h1>
                    </div>
                    <div class="breatcome-text">
                        <a href="<?php echo site_url();?>"><span>Inicio</span> Términos y condiciones</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix" style="clear: both;"></div>
<!-- ===============//breatcome section end here \\================= -->
<!--==================================================-->
<!-- Start cryptobit about Area -->
<!--==================================================-->
<div class="blog-area pt-80 pb-70">
    <div class="container">     
        <div class="row">   
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-md-12">
                        <div class="single_blog">
                             <div class="single_blog_content">
                                <div class="blog_page_title">
                                    <h4>1. Política de privacidad y Cookies</h4>  
                                </div>
                                <div class="blog_page-text">
                                <p>El presente Política de Privacidad establece los términos en que GENEX usa y protege la información que es proporcionada por sus usuarios al momento de utilizar su sitio web. Esta compañía está comprometida con la seguridad de los datos de sus usuarios. Cuando le pedimos llenar los campos de información personal con la cual usted pueda ser identificado, lo hacemos asegurando que sólo se empleará de acuerdo con los términos de este documento. Sin embargo esta Política de Privacidad puede cambiar con el tiempo o ser actualizada por lo que le recomendamos y enfatizamos revisar continuamente esta página para asegurarse que está de acuerdo con dichos cambios.</p>
                                <h5>2. Información que es recogida</h5>
                                <p>Nuestro sitio web podrá recoger información personal por ejemplo: Nombre, información de contacto como su dirección de correo electrónica e información demográfica. Así mismo cuando sea necesario podrá ser requerida información específica para procesar algún pedido o realizar una entrega o facturación.</p>
                                <h5>3. Uso de la información recogida</h5>
                                <p>Nuestro sitio web emplea la información con el fin de proporcionar el mejor servicio posible, particularmente para mantener un registro de usuarios, de pedidos en caso que aplique, y mejorar nuestros productos y servicios. Es posible que sean enviados correos electrónicos periódicamente a través de nuestro sitio con ofertas especiales, nuevos productos y otra información publicitaria que consideremos relevante para usted o que pueda brindarle algún beneficio, estos correos electrónicos serán enviados a la dirección que usted proporcione y podrán ser cancelados en cualquier momento. GENEX está altamente comprometido para cumplir con el compromiso de mantener su información segura. Usamos los sistemas más avanzados y los actualizamos constantemente para asegurarnos que no exista ningún acceso no autorizado.</p>
                                <h5>4. Cookies</h5>
                                <p>Una cookie se refiere a un fichero que es enviado con la finalidad de solicitar permiso para almacenarse en su ordenador, al aceptar dicho fichero se crea y la cookie sirve entonces para tener información respecto al tráfico web, y también facilita las futuras visitas a una web recurrente. Otra función que tienen las cookies es que con ellas las web pueden reconocerte individualmente y por tanto brindarte el mejor servicio personalizado de su web.</p>
                                <p>Nuestro sitio web emplea las cookies para poder identificar las páginas que son visitadas y su frecuencia. Esta información es empleada únicamente para análisis estadístico y después la información se elimina de forma permanente. Usted puede eliminar las cookies en cualquier momento desde su ordenador. Sin embargo las cookies ayudan a proporcionar un mejor servicio de los sitios web, estás no dan acceso a información de su ordenador ni de usted, a menos de que usted así lo quiera y la proporcione directamente, visitas a una web . Usted puede aceptar o negar el uso de cookies, sin embargo la mayoría de navegadores aceptan cookies automáticamente pues sirve para tener un mejor servicio web. También usted puede cambiar la configuración de su ordenador para declinar las cookies. Si se declinan es posible que no pueda utilizar algunos de nuestros servicios</p>
                                <h5>5. Enlaces a Terceros</h5>
                                <p>Este sitio web pudiera contener en laces a otros sitios que pudieran ser de su interés. Una vez que usted de clic en estos enlaces y abandone nuestra página, ya no tenemos control sobre al sitio al que es redirigido y por lo tanto no somos responsables de los términos o privacidad ni de la protección de sus datos en esos otros sitios terceros. Dichos sitios están sujetos a sus propias políticas de privacidad por lo cual es recomendable que los consulte para confirmar que usted está de acuerdo con estas.</p>
                                <h5>6. Control de su información personal</h5>
                                <p>En cualquier momento usted puede restringir la recopilación o el uso de la información personal que es proporcionada a nuestro sitio web. Cada vez que se le solicite rellenar un formulario, como el de alta de usuario, puede marcar o desmarcar la opción de recibir información por correo electrónico. En caso de que haya marcado la opción de recibir nuestro boletín o publicidad usted puede cancelarla en cualquier momento. Esta compañía no venderá, cederá ni distribuirá la información personal que es recopilada sin su consentimiento, salvo que sea requerido por un juez con un orden judicial.</p>
                                <p>GENEX se reserva el derecho de cambiar los términos de la presente Política de Privacidad en cualquier momento.</p>
                                </div>   
                                <div class="blog_page_title">
                                    <h4>1. MODIFICACIONES</h4>  
                                </div>
                                <div class="blog_page-text">
                                    <p>Nos reservamos el derecho en cualquier momento a:<br/></p>
                                    <p>Cambiar los términos y condiciones de este acuerdo:</p>
                                    <p>Mejorar, agregar, modificar o descontinuar el sitio u otras ofertas, o cualquier parte del sitio u otras ofertas, en cualquier momento a nuestro exclusivo criterio. De vez en cuando, nos reservamos el derecho. A nuestro exclusivo criterio, modificar, actualizar, agregar, descontinuar. eliminar, revisar o cambiar cualquier parte de este acuerdo, en su totalidad o en parte, en cualquier momento. Para los cambios a este acuerdo que consideremos importantes, colocaremos un aviso en el sitio revisando el enlace en la página de inicio para que se lea sustancialmente como 'términos de uso actualizados durante un período de tiempo razonable'. Si nos proporciona información, accede o usa el sitio o participa en cualquier oferta de alguna manera después de que este acuerdo haya sido modificado, se considerará que ha leído, entendido y dado su consentimiento incondicional y aceptado dichos cambios. La versión más actual de este acuerdo estará disponible en el sitio y reemplazará todas las versiones anteriores de este acuerdo.</p>
                                    <h5>2. USO DEL SITIO</h5>
                                    <p>Debe obtener acceso a Internet y pagar las tarifas de servicio asociadas con dicho acceso para utilizar el sitio. Además, debe proporcionar todo el equipo necesario para acceder a Internet. Usted es y seguirá siendo el único responsable de la compra, conexión, instalación, carga, operación y mantenimiento de cualquier equipo tecnológico.</p>
                                    <p>1. Hardware, software, servicio telefónico (cable u otro) y el servicio de acceso a Internet para su computadora personal y para todos los servicios relacionados. Usted es el único responsable de escanear su hardware y software en busca de virus informáticos y otros problemas relacionados antes de usarlos. Renunciamos expresamente a cualquier responsabilidad por cualquier error o falla relacionada con el mal funcionamiento o falla de su hardware o software en relación con el uso del sitio o las ofertas. A menos que se especifique lo contrario. Los sitios web de GENEX, sus afiliadas y subsidiarias son para su uso personal.</p>
                                    <p>No puede modificar, copiar, distribuir, transmitir, mostrar, reproducir publicar, licenciar, crear trabajos derivados, transferir o vender cualquier información obtenida de los sitios web de GENEX. GENEX autoriza a ver y descargar los materiales de este sitio web solo para su uso personal y no comercial, siempre que conserve todos los avisos de derechos de autor y otros avisos de propiedad contenidos en los materiales originales en cualquier copia de los materiales.</p>
                                    <p>No puede modificar los materiales de este sitio de ninguna manera ni reproducirlos, exhibirlos públicamente, ejecutarlos, distribuirlos ni utilizarlos de ninguna otra manera para ningún fin público o comercial. Para los propósitos de estos términos, se prohíbe cualquier uso de estos materiales en cualquier otro sitio web o entorno informático en red para cualquier propósito. Los materiales de este sitio están protegidos por derechos de autor y cualquier uso no autorizado de cualquier material de este sitio puede violar los derechos de autor, marcas comerciales y otras leyes. Si incumple cualquiera de estos términos, su autorización para usar este sitio termina automáticamente y debe destruir inmediatamente cualquier material descargado o impreso.</p>
                                    <p><b>2. Rescisión de este acuerdo</b></p>
                                    <p>Este acuerdo permanecerá en vigor mientras acceda al sitio web, venda o compre cualquier membresía, venda o compre cualquier paquete o solicite cualquier servicio del sitio web. Nos reservamos el derecho de rescindir este acuerdo sin previo aviso y / o negarnos a vender a cualquier persona en quien creamos, a nuestro exclusivo criterio haya violado cualquiera de los términos de este acuerdo y esté abusando de los productos o servicios que proporcionamos, o no puede proporcionarnos información suficiente que nos permita identificar correctamente el nombre real del distribuidor independiente del cliente, la dirección, el número de teléfono, la tarjeta de identificación legal o el pasajero.</p>
                                    <p>3. Individuos, corporaciones, entidades exentas de impuestos Usted declara y garantiza que tiene dieciocho y 158 años de edad o más o si es menor de dieciocho años y está accediendo al sitio con el conocimiento y el código de su padre o tutor legal, que también se considera que ha aceptado el acuerdo.Determinadas características en el sitio (incluido, entre otros, el registro de usuario y ciertas ofertas pueden ser sujeto a mayor edad / u otros requisitos de elegibilidad. GENEX solo considerará para la aceptación como miembro de la empresa, distribuidor independiente o miembro de la empresa que pertenezcan a una de las siguientes categorías: a.) Personas físicas que sean mayores de edad. B.) Parejas casadas de las que al menos una sea menor de edad. C.) Sociedades anónimas al día en el estado, provincia o país de su constitución.</p>
                                    <p>4. Completar correctamente los documentos. Todas las entradas en los sitios web de GENEX deben estar completa y correctamente y deben aceptarse mediante una marca de verificación del acuerdo de distribuidor independiente, los términos y condiciones, las políticas y los procedimientos. Las políticas de divulgación de ingresos, correo no deseado y privacidad son indicativos de una firma electrónica utilizada para firmar el acuerdo de GENEX, los términos y condiciones y la política de privacidad. GENEX no será responsable por la pérdida de comisiones o bonificaciones o por retrasos en los registros debido a: a) errores de los miembros de la empresa que envían información incorrecta para sí mismos o en nombre de los clientes. B) retrasos o errores causados por una conexión a Internet débil, virus en su computadora, ataque de piratas informáticos a su computadora bloqueando la transmisión de su registro.</p>
                                    <p><b>5. Descargo de responsabilidad.</b></p>
                                    <p>Los materiales proporcionados en este sitio se proporcionan tal cual sin ningún tipo, incluidas las garantías de comerciabilidad, idoneidad para un propósito particular o no infracción de la propiedad intelectual.</p>
                                    <p>Además, GENEX no garantiza la precisión y la integridad de los materiales de este sitio. GENEX puede realizar cambios en los materiales de este sitio, o en los productos, precios o plan de compensación descritos en ellos, en cualquier momento y sin previo aviso. Los materiales de este sitio pueden estar desactualizados y GENEX se compromete a actualizar los materiales de este sitio. La información publicada en este sitio puede referirse a productos; programas o servicios que están destinados a ser utilizados únicamente en un país específico y no pueden utilizarse ni depender de ellos en ningún otro país. Es posible que la ley aplicable no permita la exclusión de garantías implícitas, por lo que es posible que la excepción anterior no se aplique en su caso.</p>
                                    <p><b>6. Restricción de terminación / acceso.</b></p>
                                    <p>GENEX se reserva el derecho, a su entera discreción, de cancelar su acceso a cualquiera o todos los sitios web de GENEX, la oficina administrativa y los servicios relacionados o cualquier parte de los mismos en cualquier momento, sin previo aviso. Las razones para la rescisión incluyen, entre otras:</p>
                                    <p>A. Difamación, calumnia o calumnia de GENEX u otros miembros a unirse a otra empresa que promueva productos y/o servicios de moneda digital, criptográfica o productos tangibles que perjudiquen el avance de GENEX y en violación de estos términos y condiciones.</p>
                                    <p>B. Promocionar falsamente GENEX de cualquier manera que cause daños a la reputación de GENEX.</p>
                                    <p>C. Prometer o garantizar cualquier "retorno de la licencia comprada".</p>
                                    <p>D. Transmitir, publicar, enviar, cargar, distribuir, enviar o poner a disposición cualquier contenido que sea ilegal o infrinja, viole o se apropia indebidamente de cualquier patente, marca comercial, derecho de identidad comercial, secreto comercial. derecho de publicidad, derecho de privacidad, derechos de autor o cualquier otra propiedad intelectual o cualquier otro derecho de cualquier tercero.</p>
                                    <p>E. Transmitir, publicar, enviar, cargar, distribuir, enviar o poner a disposición cualquier virus, troyanos u otros archivos o material dañino, perturbador o destructivo que interfiere con el uso y disfrute del sitio por parte de terceros.</p>
                                    <p>F. Violar cualquier estado local aplicable. ley, norma o reglamento federal o internacional.</p>
                                    <p>G. Transmitir, publicar, enviar, cargar, distribuir, enviar o poner a disposición a través del sitio cualquier contenido que contenga cualquier solicitud de fondos, promoción. publicidad o solicitud de bienes o servicios. Por la presente, también reconoce que tiene prohibido solicitar a otros invitados que se unan o se conviertan en miembros de cualquier servicio comercial en línea u otra organización: 1. Recopile o recopile la información de cualquier usuario o acceda al sitio utilizando medios automatizados (que incluyen, entre otros, la recolección de bots, robots, arañas o raspadores): "marco" "espejo" o "profundo vincular cualquier parte del sitio u otras ofertas sin nuestra autorización previa por escrito.</p>
                                    <p>H. Prometer o garantizar cualquier beneficio. Prometer o garantizar ingresos pasivos usando una identidad falsa o GENEX no puede verificar la identidad o el miembro le debe dinero a la empresa.</p>
                                    <p>I. El miembro no cumplió con sus obligaciones como miembro o distribuidor. Uso no autorizado de la cuenta de otra persona</p>
                                    <p>J. Violar los términos y condiciones.</p>
                                    <p>K. Otras faltas y violaciones.</p>
                                    <p>L. Violaciones de la ley de cualquier país o estado.</p>
                                    <p>M. Cuando el socio de marca quiere concluir el contrato con nosotros puede hacerlo en cualquier momento dentro del periodo de permanencia, sin embargo, si la licencia de crypto se encuentra en gestión en los mercados de criptomoneda tendrá una penalidad del 60% del importe de la licencia al quebrantar la permanencia y afectar negativamente las operaciones con los proveedores externos.</p>
                                    <p>7. Modificación de estos términos de uso.</p>
                                    <p>GENEX puede revisar estos términos en cualquier momento actualizando esta publicación. Debe visitar esta página de vez en cuando para revisar la información actual términos porque son vinculantes para usted. Ciertas disposiciones de estos términos pueden ser reemplazado por avisos legales expresamente designados o términos ubicados en particular páginas de este sitio.</p>
                                    <p>8. Limitación de privacidad.</p>
                                    <p>En ningún caso, GENEX, sus proveedores u otros terceros mencionados en este sitio serán responsables de cualquier daño (incluidos, entre otros, los resultantes de la pérdida de beneficios, la pérdida de datos o la interrupción del negocio) que surjan del uso, la imposibilidad de utilizar , o los resultados del uso de este sitio, cualquier sitio web vinculado a este sitio, o los materiales o la información contenida en cualquiera de dichos sitios, ya sea en base a garantía, contrato, agravio o cualquier otra teoría legal y ya sea o no informado de la posibilidad de tales daños, si su uso de los materiales o la información de este sitio resulta en la necesidad de servicio, reparación o corrección de equipos o datos, usted asume todos los costos de los mismos: la ley aplicable puede no permitir la exclusión o limitación de incidentes o daños consecuentes, por lo que es posible que la limitación o exclusión anterior no se aplique a usted.</p>
                                    <p>9. Indemnización</p>
                                    <p>Usted acepta defender, indemnizar y eximir de responsabilidad a GENEX, sus funcionarios, directores, accionistas, empleados, contratistas independientes, proveedores de telecomunicaciones y agentes, de y contra todos y cada uno de los reclamos, acciones, pérdidas, responsabilidades, gastos, costos o demandas. , Incluyendo, entre otros, los honorarios legales y contables, por todos los daños directos, indirectos y / o consecuentemente resultantes o supuestamente resultantes de su mal uso o incapacidad para usar el sitio web, o su incumplimiento de cualquiera de estos términos y condiciones de este acuerdo. Le notificaremos de inmediato por correo electrónico sobre cualquier reclamo o demanda, y cooperaremos completamente (a su cargo) en la defensa de tal reclamación o demanda. Si no recibimos noticias suyas de inmediato, nos reservamos el derecho de defender tal reclamo o demanda y buscar una recompensa completa de usted.</p>
                                    <p>Nadie está autorizado para acceder a este sitio o utilizar los servicios a menos que él, ella o él haya firmado este acuerdo. Dicha firma no necesita ser una firma física, ya que la aceptación electrónica de este acuerdo está permitida por las leyes de varias jurisdicciones, como las firmas electrónicas en la ley de comercio global y nacional (ley de firma electrónica) y legislación similar. Usted manifiesta su aceptación de este acuerdo tomando cualquier acto que demuestre su consentimiento al mismo. Lo más probable es que haya hecho clic o hará clic en un botón que contiene las palabras "Estoy de acuerdo o alguna sintaxis similar. Debe comprender que esto tiene el mismo efecto legal que si coloca su firma física en cualquier otro contrato legal. Si hace clic en cualquier botón de vínculo u otro dispositivo que se le proporcione en cualquier parte de la interfaz de nuestro sitio, entonces usted ha aceptado legalmente todos estos términos y condiciones. Además, al utilizar cualquier parte de nuestro sitio o servicios de cualquier manera, incluido el intercambio, usted comprende y acepta que tal uso constituye su afirmación de su completa e incondicional nadie está autorizado o autorizado para acceder a este sitio o utilizar los servicios a menos que él, ella o él haya firmado este acuerdo. Dicha firma no necesita ser una firma física ya que la aceptación electrónica de este acuerdo permitido por varias jurisdicciones leyes tales como las firmas electrónicas y la ley de comercio nacional no aceptación de todos los términos del acuerdo Incluso si Si acepta firmar este acuerdo, comprende y acepta que aún está sujeto a los términos de este acuerdo en virtud de que visita el sitio o utiliza cualquier parte del sitio o nuestros servicios.</p>
                                    <p>10. No es una cuenta bancaria o fiduciaria, su cuenta con nosotros (y cualquier moneda disponible en la misma) no es una cuenta bancaria, una cuenta fiduciaria, una cuenta de valores, una tarjeta de crédito o una cuenta de depósito. Nuestros servicios no son instrumentos financieros. No se pagarán intereses sobre ningún fondo o moneda que utilice para comprar o intercambiar por cualquier otra moneda, bitcoin o cualquier otra cosa con otros miembros, y todos los activos, incluida dicha moneda o bitcoin, que estén directamente en poder de la empresa no son asegurado por la empresa o cualquier agencia gubernamental. Toda la moneda comprada y vendida por usted se asociará con su cuenta hasta que se use para comprar o vender de o con otros. miembros o hasta que usted lo retire. Descargo de responsabilidad: factores de riesgo GENEX no es responsable de ninguna pérdida o daño incurrido por usted como resultado de su uso de nuestros servicios o por su falta de comprensión de la naturaleza de las monedas virtuales o el mercado de dichas monedas. Todo lo que le brindamos es un método mediante el cual puede intercambiar, comerciar y almacenar ciertas monedas virtuales, y no hacemos declaraciones ni garantías con respecto al valor, la estabilidad o la legalidad de dichas monedas virtuales.</p>
                                    <p>11. USTED RECONOCE LOS SIGUIENTES RIESGOS RELACIONADOS CON EL USO DEL SITIO Y SERVICIOS:</p>
                                    <p>12. El riesgo de pérdida en el comercio de monedas virtuales como bitcoin (colectivamente, "digital activos) pueden ser sustanciales y las pérdidas pueden ocurrir en un corto período de tiempo.</p>
                                    <p>13. El precio y la liquidez de los activos digitales han estado sujetos a grandes fluctuaciones en pasado y pueden estar sujetos a grandes fluctuaciones en el futuro. Los activos digitales no son moneda de curso legal, no están respaldados por ningún gobierno, y las cuentas y los saldos de valor no están sujetos a las protecciones de las corporaciones de seguros de depósitos federales o de las corporaciones de protección de inversores de valores. Los cambios legislativos y reglamentarios o las acciones a nivel estatal, federal o internacional pueden afectar negativamente el uso, la transferencia, el intercambio y el valor de los activos digitales.</p>
                                    <p>14. Las transacciones en activos digitales pueden ser irreversibles y, en consecuencia, las pérdidas debidas a transacciones fraudulentas o accidentales pueden no ser recuperables.</p>
                                    <p>15. Algunas transacciones de activos digitales se considerarán realizadas cuando se registren en un libro público, que no es necesariamente la fecha u hora en que el cliente inicia las transacciones.</p>
                                    <p>16. El valor de los activos digitales puede derivarse de la voluntad continua de los participantes del mercado de intercambiar monedas fiduciarias por activos digitales, lo que puede resultar en la posibilidad de una pérdida permanente y total del valor de una moneda virtual en particular si el mercado de esa moneda virtual desaparecer.</p>
                                    <p>17. No hay garantía de que una persona que acepta activos digitales como pago hoy continúe haciéndolo en el futuro.</p>
                                    <p>18. La naturaleza de los activos digitales puede conducir a un mayor riesgo de fraude o ciberataque, y puede significar que las dificultades tecnológicas experimentadas por la empresa pueden impedir el acceso o uso de sus activos digitales.</p>
                                    <p>19. Su cuenta con GENEX puede no ser suficiente para cubrir todas las pérdidas sufridas por usted. Usted reconoce y acepta que es el único responsable de determinar la naturaleza, el valor potencial, la idoneidad y la conveniencia de esos riesgos para usted, y que GENEX no brinda consejos ni recomendaciones con respecto a los activos digitales, incluida la idoneidad y conveniencia de las estrategias de inversión para activos digitales.</p>
                                    <p>20. Usted reconoce y acepta que accederá y utilizará los servicios y el sitio bajo su propio riesgo. Esta breve declaración no revela todos los riesgos asociados con el comercio, el intercambio y el almacenamiento de activos digitales. Debería. por lo tanto, considere cuidadosamente si dicho comercio, intercambio y almacenamiento son adecuados para usted a la luz de sus circunstancias y recursos financieros. Debe tener en cuenta que puede sufrir una pérdida total de los fondos de su cuenta (como se define a continuación) y que, en determinadas condiciones de mercado, puede resultarle difícil o imposible liquidar una posición.</p>
                                    <p>21. Valores de moneda virtual, usted comprende y acepta que, debido a restricciones técnicas y de otro tipo, los valores de la moneda virtual que se muestran en nuestro sitio pueden retrasarse y, por lo tanto, no reflejan el valor de mercado actual y en vivo de dicha moneda. No obstante, acepta que los valores que se muestran en nuestro sitio controlan su cuenta y su uso del sitio y los servicios</p>
                                    <p>22. Datos de registro de su cuenta. Para utilizar los sistemas GENEX, debe crear una cuenta con nosotros (su 'cuenta'). Su cuenta se utilizará para almacenar varias cantidades de moneda virtual depositadas por usted. Al crear su cuenta, es posible que se le solicite que proporcione ciertos detalles e información de registro. Para verificar su identidad, parte de esta información puede ser personal, privada o detallada. En relación con completar el formulario de registro en línea, usted acepta proporcionar información verdadera, precisa, actual y completa sobre usted según lo solicite el formulario de registro (dicha información son los 'datos de registro); y además acepta mantener y con prontitud. Actualice los datos de registro para mantenerlos verdaderos, precisos, actualizados y completos en todo momento mientras sea miembro. Si bien hacemos todos los esfuerzos razonables para proteger la información personal de otros de la divulgación involuntaria o la apropiación indebida, no somos responsables de los actos intencionales o criminales de terceros, como piratas informáticos o 'phishers'.</p>
                                    <p>23. Cambios en los datos de registro, debe informarnos / actualizarnos de inmediato de todos los cambios, incluidos, entre otros, los cambios en su dirección y los cambios en cualquier cuenta de moneda virtual o fiduciaria utilizada por usted en relación con el sitio y los servicios, si corresponde. Si proporciona información que es falsa, inexacta, no actual o incompleta, o si nosotros o cualquiera de nuestros agentes autorizados tenemos motivos razonables para sospechar que dicha información es falsa, inexacta, no actual o incompleta, tenemos el derecho de suspender o cancelar su cuenta y rechazar cualquier uso actual o futuro del sitio y los servicios por su parte, así como someterlo a responsabilidad civil o remitirlo a las autoridades policiales apropiadas para el procesamiento penal. No seremos responsables de hacer ninguna compensación, monetaria o propia, después de mucha suspensión, rescisión o incapacidad para utilizar el sitio o los servicios. Usted comprende y acepta que, debido a restricciones técnicas y de otro tipo, los valores de la moneda virtual que se muestran en nuestro sitio pueden retrasarse y, por lo tanto, no reflejan el valor de mercado actual y en vivo de dicha moneda. No obstante, acepta que los valores que se muestran en nuestro sitio controlan su cuenta y su uso del sitio y los servicios.</p>
                                    <p>24. Responsabilidad de su cuenta Usted es el único responsable de todas y cada una de las actividades realizadas a través de su cuenta. Usted acepta notificarnos inmediatamente de cualquier uso no autorizado de su contraseña o identificación de miembro, así como de cualquier otra violación de seguridad. Si bien podemos implementar ciertos procedimientos de monitoreo diseñados para alertarnos sobre actividades fraudulentas, no somos responsables de ningún uso no autorizado de su cuenta, y usted acepta que es responsable de dicho uso no autorizado y de proteger la confidencialidad de su contraseña. Al final de su período de membresía de 150 días a más, usted es responsable de renovar si desea continuar con GENEX y el uso de sus servicios y software.</p>
                                    <p>25. Seguridad de la contraseña: Como parte de nuestras medidas y políticas de seguridad, tenga en cuenta que nunca le preguntaremos, por ningún motivo, ya sea por correo electrónico, correo ordinario o teléfono, para divulgar la contraseña de su cuenta. Las consultas sobre contraseñas solo se realizarán en línea y solo después de que se haya registrado en el sitio de la empresa. Nunca le enviaremos enlaces incrustados en un correo electrónico solicitando que inicie sesión en el sitio haciendo clic en dicho enlace. Si recibe un enlace incrustado por correo electrónico, afirmando ser de nosotros, no debe abrirlo ni hacer clic en el enlace. El correo electrónico no proviene de nosotros y es probable que sea fraudulento. Nunca dé su cuenta o contraseña a cualquier persona a quien no tenga la intención de autorizar el uso de su cuenta. Información de la cuenta de terceros para brindarle los servicios, es posible que también se le solicite que nos revele cierta información de la cuenta de terceros, incluidas, entre otras, sus direcciones de bitcoin e información relacionada. Como se indica en otra parte de este acuerdo, no somos responsables de ningún uso no autorizado de su cuenta con la empresa o cuentas de terceros.</p>
                                    <p>26. Cómo depositar fondos en su cuenta después de crear su cuenta con GENEX, podrá depositar fondos en su cuenta transfiriendo, desde su cuenta bitcoin a la cuenta GENEX, no cobramos comisiones por depositar fondos en su cuenta. Después de financiar su cuenta, tome una captura de pantalla de la transferencia y cárguela.</p>
                                    <p>27. No hay reversión de transacciones, depósitos o pagos.</p>
                                    <p>Una vez que se haya ejecutado una orden (transferir de usuario a usuario, depositar btc en su billetera de efectivo o solicitud de pago) y las monedas correspondientes se hayan abonado y debitado de las cuentas de los miembros, no podremos revertir la transacción en ninguna circunstancia.</p>
                                    <p>28. Interrupción del servicio. De vez en cuando debido a factores tecnológicos, cargas de software programadas y otros factores fuera de nuestro control o fuera de nuestro control, el sitio u otros servicios pueden interrumpirse temporalmente. Usted acepta que no somos responsables de ninguna pérdida o daño que surja de dicha Interrupción y acepta eximirnos de toda responsabilidad contra dicha interrupción o imposibilidad de acceder al sitio o los servicios.</p>

                                    <p>29. Retiro de moneda. Además de permitir que los miembros intercambien moneda virtual, GENEX permite a los miembros retirar moneda virtual cuando lo solicitemos. Los miembros pueden retirar la totalidad o parte de su moneda virtual, y no se requiere una cantidad mínima de moneda virtual para mantener su estado como miembro (sin embargo, como se indicó anteriormente, solo puede comerciar o vender moneda virtual hasta la cantidad que se muestra como perteneciente a usted en el libro mayor guardado en su billetera). La moneda abc se transferirá de la cuenta del intercambio a la dirección de bitcoin específica proporcionada por el miembro. Los retiros generalmente demorarán hasta tres (3) días hábiles en completarse, siempre que los retiros más grandes puedan demorar hasta treinta (30) días hábiles en completarse y que cualquier retiro pueda demorarse según sea necesario para cumplir con la ley aplicable y / o las Procedimientos de identificación de clientes y antilavado de dinero.</p>
                                    <p>30. GENEX no se dedica a la venta de valores o inversiones de ningún tipo. Usted comprende y acepta que:</p>
                                    <p>a) GENEX no se dedica a la venta u oferta de valores.</p>
                                    <p>b) Esta no es una oferta de venta de un valor, contrato de inversión, oportunidad de inversión, oferta, etc., o instrumento de fideicomiso, según la definición de los estados unidos ley de valores de 1933, según enmendada, así como cualquier ley o reglamento de cualquier país, estado o territorio.</p>
                                    <p>c) GENEX no se registrará como sociedad de inversión en virtud de la inversión ley de sociedades de 1940, según enmendada.</p>
                                    <p>d) Al tomar su decisión de comprar una membresía en GENEX, debe confiar en su propio examen de los términos del acuerdo, incluidos los méritos y riesgos involucrados. GENEX pondrá a disposición de cualquier miembro potencial de GENEX la oportunidad de hacer preguntas y recibir respuestas de GENEX con respecto a la membresía y los términos y condiciones de esta membresía y de obtener cualquier información adicional relevante en la medida en que GENEX posea dicha información o pueda obtenerla. sin esfuerzo o gasto razonable.</p>
                                    <p>e) Los términos y condiciones y los derechos de membresía de GENEX no constituyen una oferta o solicitud en ninguna jurisdicción en la que dicha oferta o solicitud no esté autorizada o permitida por la ley.</p>
                                    <p>f) Si alguna parte de los términos de GENEX fuera considerada por cualquier tribunal como un valor, los términos ofrecidos por el presente no han sido registrados bajo la ley de valores de 1933, según enmendada, o las leyes de valores de ciertos estados y se están ofreciendo y vendido con base en las exenciones de los requisitos de registro de dicha ley y dichas leyes. Los valores no han sido aprobados o desaprobados por la comisión de valores y cambio, ninguna comisión estatal de valores o cualquier otra autoridad reguladora, ni ninguna de las autoridades anteriores ha aprobado o respaldado los méritos de esta oferta o la precisión o idoneidad de este memorando. , Cualquier manifestación en contrario es ilegal.</p>
                                    <p>g) Los miembros de GENEX deben ser conscientes de que se les puede exigir que asuman los riesgos de esta compra durante un período de tiempo considerable.</p>
                                    <p>h) La pertenencia a GENEX implica riesgos importantes. GENEX no se registrará como una empresa de inversión y, por lo tanto, no se le exigirá que se adhiera a ninguna política de inversión en virtud de la ley de sociedades de inversión de 1940, según enmendada.</p>

                                    <p>i) La pertenencia a GENEX conlleva riesgos sustanciales y no se puede garantizar que se alcanzarán los objetivos de GENEX. Las prácticas de GENEX pueden emplearse de vez en cuando puede, en determinadas circunstancias, aumentar el impacto adverso al que la cuenta de los miembros puede estar sujeta.</p>
                                    <p>j) Se advierte a los miembros potenciales que se refieran a estos términos y condiciones para una discusión de los términos de membresía y riesgo y otros factores relacionados con la membresía en GENEX. Los términos y condiciones contenidos en este documento serán los que controlen.</p>
                                    <p>k) Los miembros potenciales deben considerar los siguientes factores para determinar si comprar una membresía: a) falta de historial operativo GENEX es una entidad recién formada y no tiene un historial operativo sobre el cual los miembros puedan evaluar el desempeño probable de la empresa.</p>
                                    <p>l) Negocio dependiente del valor de bitcoin.</p>
                                    <p>m) Los miembros individuales y distribuidores de GENEX no son propietarios / inversores ni otra relación que se considere de titularidad de GENEX.</p>
                                    <p>o) No hay garantía o representación de que el plan o programa de GENEX sea exitoso.</p>
                                    <p>p) Los miembros de GENEX pueden comprar y vender bitcoins y membresías entre sí sin transferir dicho dinero directamente a GENEX siempre que las membresías compradas se creen en nombre del comprador y el miembro reciba su membresía. Los miembros pueden utilizar dicho fondo como mejor les parezca y los compradores no tienen ningún recurso de que creen que el dinero fluiría directamente a GENEX.</p>
                                    <p>q) Compradores de dicha membresía tiene cualquier derecho a reclamar que pensaba que el dinero de su compra iría directamente a GENEX. Si bien los valores de mercado de divisas virtuales que se muestran públicamente en el sitio pueden retrasarse, podemos ofrecer acceso a datos de valor de mercado en vivo a través de medidas técnicas como el protocolo de corrección (intercambio de información financiera). Estos datos de valor de mercado en vivo son valiosos para nosotros, y tomamos medidas patentadas para mantener todos los datos de valor de mercado en vivo confidenciales e inaccesibles para el público. En la medida en que reciba acceso a dichos datos en vivo, por la presente acepta que no redistribuirá, retransmitirá, duplicará ni pondrá a disposición dichos datos de ninguna manera, ya sea de forma automática, manual o por cualquier otro medio. Cualquier distribución o transmisión de nuestros valores de mercado en vivo constituye un incumplimiento sustancial de este acuerdo, así como una violación de nuestros secretos comerciales. Usted acepta que no somos responsables de ninguna falla o interrupción en los datos de valor de mercado en vivo proporcionados por nosotros.</p>
                                    <p>31. Acuerdo para recibir notificaciones y otras comunicaciones nos reservamos el derecho de enviarle correo electrónico u otros mensajes a usted ya otros miembros. El propósito de estas comunicaciones puede incluir, entre otros:</p>
                                    <p><em>(i) Proporcionarle información sobre su cuenta.</em></p>
                                    <p><em>(ii) Proporcionarle información sobre productos o servicios ofrecidos por nuestras afiliadas o socios.</em></p>

                                    <p><em>(iii) Informarle sobre cualquiera de nuestros productos o servicios relacionados; o proporcionando.</em></p>
                                    <p><em>(iv) Usted con información sobre cualquier artículo que pensamos, a nuestro exclusivo criterio, puede ser de interesarle.</em></p>
                                    <p><em>(v) Proporcionarle información sobre cualquier actualización en la política de privacidad o nuestros términos y condiciones documentan las divulgaciones.</em></p>
                                    <p>32. Restricciones de uso sin nuestra autorización expresa previa por escrito, no podrá:</p>
                                    
                                    <p>(I) Duplicar cualquier parte de nuestro sitio o los materiales contenidos en el mismo o recibidos a través de los servicios (excepto que se indique expresamente en otra parte de este acuerdo).</p>
                                    <p>(II) Crea cualquier trabajo derivado basado en nuestro sitio o cualquiera de los materiales contenidos en el mismo o recibido a través de los servicios, y usted acepta y estipula que todos y cada uno las obras derivadas no son de "uso justo".</p>
                                    <p>(III) Utilizar nuestro sitio o servicios, o cualquiera de los materiales contenidos en ellos, para cualquier público exhibición, representación pública, venta o alquiler, y por la presente acepta y estipula que todos y cada uno de esos usos no son "uso justo".</p>
                                    <p>(IV) Redistribuir nuestro sitio o cualquiera de los materiales contenidos en el mismo o recibidos a través de los servicios, y por la presente acepta y estipula que todos y cada uno de dichos usos no es "uso justo".</p>
                                    <p>(V) Eliminar cualquier aviso de derechos de autor u otros avisos de propiedad de nuestro sitio o de cualquiera de los materiales contenidos en el mismo;</p>
                                    <p>(VI) Enmarcar o utilizar cualquier técnica de enmarcado en relación con nuestro sitio o cualquiera de los materiales contenidos en el mismo;</p>
                                    <p>(VII) Utilizar cualquier metaetiqueta, publicidad de pago por clic o cualquier otro Texto oculto que usa el nombre o las marcas de nuestro sitio, y por la presente estipula que cualquier uso del nombre o las marcas del sitio, o cualquier otra marca de nuestra propiedad, es una infracción de nuestros derechos de marca registrada, y usted estipula hacer el pago de daños liquidados de diez mil dólares ($ 10,000) por dicha infracción como una preestimación genuina de la pérdida y el daño que sufriremos como resultado de dicha infracción, además de que acepta pagar todos y cada uno de los honorarios incurridos en la recuperación de esta cantidad, incluidos los gastos de abogado tarifas y todos los costos asociados;</p>
                                    <p>(VIII) 'Enlace profundo a cualquier página de nuestro sitio, o evitar el acuerdo con los términos y condiciones del sitio (para evitar dudas, solo puede vincular a la página de entrada principal).</p>
                                    <p>(IX) Eludir cualquier cifrado u otro. herramientas de seguridad utilizadas en cualquier lugar del sitio o junto con los servicios (incluido el robo de nombres de usuario y contraseñas o el uso del nombre de usuario y la contraseña de otra persona para obtener acceso a un área restringida del sitio): (x) utilizar cualquier extracción de datos, bots, raspadores o herramientas similares de recopilación y extracción de datos en el sitio o junto con los servicios;</p>
                                    <p>(X) Vender, alquilar, arrendar, otorgar licencias, sublicenciar, transferir, distribuir, retransmitir, compartir en tiempo compartido, utilizar como oficina de servicios o asignar a terceros los materiales o servicios o cualquiera de sus derechos de acceso y uso. los materiales o servicios otorgados específicamente por este acuerdo:</p>
                                    <p>(XI) Utilizar nuestros servicios para cualquier propósito comercial a menos que lo acordamos expresamente por escrito y a nuestro exclusivo criterio; (xIII) utilizar nuestros servicios para hacerse pasar por cualquier otro usuario o persona; utilizar cualquier material o información en nuestro sitio o incluido en nuestros servicios de cualquier manera que infrinja cualquier derecho de autor, marca registrada, patente, secreto comercial, publicidad u otro derecho de propiedad de cualquier parte;</p>
                                    <p>(XII) Cargar o intentar cargar archivos que contengan virus, troyanos, gusanos que puedan dañar el funcionamiento de la propiedad ajena; bombas de tiempo, bots de cancelación, archivos corruptos o cualquier otro software o programa similar</p>
                                    <p>(XIII) Cargar, publicar, enviar por correo electrónico o transmitir cualquier envío que no tenga derecho a transmitir en virtud de relaciones contractuales, fiduciarias o de otro tipo (como información privilegiada, secretos comerciales, información confidencial y de propiedad adquirida o divulgada como parte de relaciones laborales o bajo acuerdos de no divulgación);</p>
                                    <p>(XIV) Cargar, publicar, enviar por correo electrónico o transmitir cualquier publicidad no solicitada o no autorizada, materiales promocionales, 'correo basura', 'spam', 'cartas en cadena', esquemas piramidales o cualquier otra forma de solicitud, excepto en aquellas áreas que podamos designar para tal fin;</p>

                                    <p>(XV) Falsificar o eliminar cualquier atribución de autor, avisos legales o de otro tipo o designaciones de propiedad o etiquetas del origen o material de origen que usted cargue o proporcione de otro modo.</p>
                                    <p>(XVI) Restringir o inhibir a cualquier otro usuario del uso y disfrute de los servicios.</p>
                                    <p>(XVII) Recolectar o recopilar información sobre otros, incluido el correo electrónico direcciones u otra información de identificación personal.</p>
                                    <p>(XVIII) Violar las leyes, políticas o regulaciones aplicables</p>
                                    <p>(XIX) Cargar, publicar, enviar por correo electrónico o transmitir cualquier material que sea ilegal, inmoral, obsceno o difamatorio de cualquier persona o</p>
                                    <p>(XX) Hacer cualquier cosa que pueda afectar negativamente el funcionamiento adecuado del sitio, los servicios y la reputación y la buena voluntad de la empresa.</p>
                                    <p>33. Después de los primeros treinta días de membresía, los miembros no podrán ser miembros o representantes de ventas de ninguna empresa de marketing multinivel involucrada en la venta o distribución de ninguna criptomoneda. Si GENEX determina que usted ha violado este término, se le notificará y se le dará la oportunidad de curarse.</p>
                                </div> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--==================================================-->
<!-- End cryptobit about Area -->
<!--==================================================-->

<!--==================================================-->
<!-- Start Cryptobit Footer Middle Area -->
<!--==================================================-->
<?php echo view("footer");?>
<!--==================================================-->
<!-- End Cryptobit Footer Middle Area -->
<!--==================================================-->
<!--==================================================-->
<!-- Start scroll Area -->
<!--==================================================-->
<div class="scroll-area">
    <div class="top-wrap">
        <div class="go-top-btn-wraper">
            <div class="go-top go-top-button">
                <i class="fas fa-arrow-up"></i>
                <i class="fas fa-arrow-up"></i>
            </div>
        </div>
    </div>
</div>
<!--==================================================-->
<!-- Start scroll Area -->
<!--==================================================-->
<?php echo view("footerjs");?>
</body>
</html>